services:
  postgres_18:
    image: postgres:18.2-alpine3.23
    container_name: postgres_tpi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres1234"
    ports:
      - "5432:5432"
    volumes:
      - ~/Docker/tpi_2026/data:/var/lib/postgresql/data
    networks:
      - network_tpi
  pgadmin_9:
    image: dpage/pgadmin4:9.12
    container_name: pgadmin_tpi
    environment:
      PGADMIN_DEFAULT_EMAIL: "correo@ues.edu.sv"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin1234"
      PGADMIN_LISTEN_PORT: "5050"
    ports:
      - "5050:5050"
    networks:
      - network_tpi
networks:
  network_tpi:
